### ISSUE TITLE
The data extracted from the app isn't working

### ISSUE THREAD

**Issue by nguyenhuutuananh** [JustKemForFun/ZaloDataExtractor#1]
As I mentioned in the title, I got an error when using that data.

P/s: Latest commit

<img width="732" alt="image" src="https://github.com/user-attachments/assets/4df9b400-8ab7-4f00-b54f-e5c5f770a985">
<img width="935" alt="image" src="https://github.com/user-attachments/assets/a190118e-cbb5-42d8-8b78-57f64689c443">
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/8f066a83-0d04-407e-be93-982944335024">

**Comment by JustKemForFun** [comment]
cho mình hỏi bạn dùng trình duyệt nào thế, bên mình dùng Chrome thì kh thấy có vấn đề bị undefined như trong ảnh cookie của bạn

**Comment by nguyenhuutuananh** [comment]
> cho mình hỏi bạn dùng trình duyệt nào thế, bên mình dùng Chrome thì kh thấy có vấn đề bị undefined như trong ảnh cookie của bạn

Mình dùng chrome Version 128.0.6613.138 và bật chế độ tab ẩn danh

**Comment by JustKemForFun** [comment]
bạn tắt ẩn danh đi thử lại giúp mình nhé, xem còn undefined thì báo lại cho mình tối về mình sẽ xem lại

**Comment by nguyenhuutuananh** [comment]
mình tắt chế độ ẩn danh thì không còn bị xuất hiện undefined nữa, cảm ơn bạn
